name: Build and Upload Artifacts

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: dotnet build /p:EnableWindowsTargeting=true -c release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: ExtraIsland/bin/Release/
